version: v2

tasks:
  build:
    runner: razorci/python:3.9
    steps:
    - checkout
    - cache/pull: pip-deps-{{ checksum "requirements.txt" }}
    - commands: 
      - python -c 'import site; print(site.getsitepackages())'
      - pip install -r requirements.txt
    - commands:
      - python test.py
    - cache/push: 
        key: pip-deps-{{ checksum "requirements.txt" }}
        paths:
        - /usr/local/lib/python3.9/site-packages
    - reports/junit: test-reports/*.xml
    - commands:
      - |
   sonar-scanner \
  -Dsonar.projectKey= python \
  -Dsonar.sources=. \
  -Dsonar.host.url=http://13.233.98.144:9000 \
  -Dsonar.login=bc4c87d4458ba8693212b09e217dcfa29e2bda0e
